// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbl9XpylCQyJMln79rL_-rWlBA8BQWHF8',
    appId: '1:63815978887:web:a770218f92f8fb55f58d22',
    messagingSenderId: '63815978887',
    projectId: 'news-app-5066d',
    authDomain: 'news-app-5066d.firebaseapp.com',
    storageBucket: 'news-app-5066d.appspot.com',
    measurementId: 'G-YYJ5FCN2RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZh47HsZzkcZtVmzkpRUiQMSwIIFODH30',
    appId: '1:63815978887:android:285199e4abeb1b88f58d22',
    messagingSenderId: '63815978887',
    projectId: 'news-app-5066d',
    storageBucket: 'news-app-5066d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDzss1TC8iG0BLNTEx17zfkazBdoTQ9vA',
    appId: '1:63815978887:ios:16e5e2810eebc635f58d22',
    messagingSenderId: '63815978887',
    projectId: 'news-app-5066d',
    storageBucket: 'news-app-5066d.appspot.com',
    androidClientId: '63815978887-o8e5bfqte6k58c3c6h7f494id4unf4fb.apps.googleusercontent.com',
    iosClientId: '63815978887-hdbs08hnlie6mb62a63j6fe6uhvaf3mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.newshub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDzss1TC8iG0BLNTEx17zfkazBdoTQ9vA',
    appId: '1:63815978887:ios:16e5e2810eebc635f58d22',
    messagingSenderId: '63815978887',
    projectId: 'news-app-5066d',
    storageBucket: 'news-app-5066d.appspot.com',
    androidClientId: '63815978887-o8e5bfqte6k58c3c6h7f494id4unf4fb.apps.googleusercontent.com',
    iosClientId: '63815978887-hdbs08hnlie6mb62a63j6fe6uhvaf3mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.newshub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT98JzAR9bh9IVG46-8GhhLX43ZFVYuD8',
    appId: '1:63815978887:web:f2ec90ce084b8d66f58d22',
    messagingSenderId: '63815978887',
    projectId: 'news-app-5066d',
    authDomain: 'news-app-5066d.firebaseapp.com',
    storageBucket: 'news-app-5066d.appspot.com',
    measurementId: 'G-HENETK4MJQ',
  );
}
